### ISSUE TITLE
[dashing] hard dependency on opensplice

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2-gbp/rmw_implementation-release#1]
In dashing `rmw_implementation` has a hard dependency on both `rmw_opensplice_cpp` and `rmw_fastrtps_cpp`:

https://github.com/ros2-gbp/rmw_implementation-release/blob/32d6e9bbb0dbee8e1ae8ceb2481f1278b84228ba/debian/control#L11

We can see unconditional rules `ros-dashing-rmw-fastrtps-cpp` and `ros-dashing-rmw-opensplice-cpp`, before the conditional rule `ros-dashing-rmw-fastrtps-cpp | ros-dashing-rmw-connext-cpp | ros-dashing-rmw-opensplice-cpp `.

This result in **opensplice always being installed** for any package above rmw_implementation.

In previous releases only the conditional rule was present:
https://github.com/ros2-gbp/rmw_implementation-release/blob/46cc619ead860180e0da467586896c24f4357b64/debian/control#L11

@mjcarroll @nuclearsandwich  FYI

**Comment by nuclearsandwich** [comment]
The patch to depend on any one rmw implementation is present for Dashing in 07866d7b502f45473a128f1beccdf448c8f1f54b, but yeah the overlaid package.xml interferes.

#2 and a pkgrev should resolve this issue for the next sync.

**Comment by nuclearsandwich** [comment]
https://github.com/ros/rosdistro/pull/21448

The release will be in the next sync or patch release of Dashing. No ETA

**Comment by mikaelarguedas** [comment]
Thanks for the express release and the headsup :+1:
